### ISSUE TITLE
can't connect with server

### ISSUE THREAD

**Issue by Lianathanoj** [wcheung8/CS-4400_Phase_3#2]
tried with user asdf. This didn't really matter as I was just changing layouts, but I got a com.mysql.jdbc.exceptions.jdbc4.CommunicationsException

**Comment by wcheung8** [comment]
have you tried reading the instructions in resources?

**Comment by wcheung8** [comment]
you have to be on the gatech vpn to access the database

**Comment by Lianathanoj** [comment]
yeah i was being dumb, figured it out already so i closed the request
